image: gcc

build:
  stage: build
  script:
    - git submodule update --init libtmsolve
    - gcc ./*.c ./libtmsolve/src/*.c -I./libtmsolve/include -Wall -lm -lreadline -D LOCAL_BUILD -D USE_READLINE -O2 -o ./tmsolve
  artifacts:
    paths:
      - tmsolve

# run tests using the binary built before
test:
  stage: test
  script:
    - ./tmsolve --test ./calc_tests.txt

#deploy:
#  stage: deploy
#  script: echo "Define your deployment script!"
#  environment: production
