image: gcc

build:
  stage: build
  script:
    - git submodule update --init libtmsolve
    - gcc ./*.c ./libtmsolve/src/*.c -I./libtmsolve/include -Wall -lm -lreadline -D LOCAL_BUILD -D USE_READLINE -O2 -o ./tmsolve
  artifacts:
    paths:
      - tmsolve

# run tests using the binary built before
test accuracy:
  stage: test
  script:
    - ./tmsolve --test ./tests/accuracy_test.txt

test resilience:
  stage: test
  script:
    - ./tmsolve < ./tests/resilience_test.txt

#deploy:
#  stage: deploy
#  script: echo "Define your deployment script!"
#  environment: production
